device_class1="LPC"
device_lpc_cmd="cmdx.py reg_read 0x727 1"
device_lpc_name1="tcs82-100f"
device_lpc_name2="bs100r0"
device_lpc_name3="b6920-4c"
device_lpc_name4="b6510-32cq"
device_lpc_name5="tcs83-100f"
device_lpc_name6="b6580-24dc8qc"
device_lpc_name7="b6580-48cq8qc"
device_lpc_name8="tcs8400"
device_lpc_name9="b6980-64qc"
device_lpc_name10="tcs9400"
device_lpc_master="01"
device_lpc_slave="02"


device_class2="I2C_BUS0"
device_i2c_bus0_cmd="i2cget -f -y 0 0x0d 0x20"
device_i2c_bus0_name1="tcs81-100f"
device_i2c_bus0_name2="b6510-48vs8cq"
device_i2c_bus0_master="0x00"
device_i2c_bus0_slave="0x01"

device_class3="I2C_BUS2"
device_i2c_bus2_cmd="i2cget -f -y 2 0x0d 0x20"
device_i2c_bus2_name1="BC10072"
device_i2c_bus2_name2="BT2575"
device_i2c_bus2_name3="b6520-64cq"
device_i2c_bus2_master="0x00"
device_i2c_bus2_slave="0x01"
